### ISSUE TITLE
Tracing level

### ISSUE THREAD

**Issue by elpiel** [storyscript/tracing-wasm#28]
I couldn't find any documentation or information on how to set the maximum tracing level.
It would be nice to be able to set it when building package or when using it, however, I'm not sure how this could be passed to wasm.

I've tried using `RUST_LOG` (`tracing-subscriber = { version = "0.3", features = ["env-filter"] }`) but it doesn't seem to do anything for the package itself when using it with `wasm-pack` (only sets verbosity of wasm-pack itself).

**Comment by kalzoo** [comment]
https://docs.rs/tracing-wasm/0.2.1/tracing_wasm/struct.WASMLayerConfigBuilder.html

```rust
    let layer_config = WASMLayerConfigBuilder::new()
        .set_max_level(tracing::Level::WARN)
        .build();
    tracing::subscriber::set_global_default(Registry::default().with(WASMLayer::new(layer_config)))
        .expect("default global");
```

**Comment by elpiel** [comment]
Thank you @kalzoo ,
What I meant is for a way to change the tracing level with an env. variable instead of  inside the code itself.
I believe there is no way to do it so I'm closing this issue.

**Comment by colelawrence** [comment]
Yeah, I think it might be possible to set it via tracing feature flags, though https://docs.rs/tracing/latest/tracing/level_filters/index.html#compile-time-filters

I must assume you mean setting the logging level at compile time, because in the actual WASM, we won't have your env vars.


This is a cool piece of documentation that could be added though.

**Comment by elpiel** [comment]
I was actually hoping you could do it with env. variable somehow.
But yes, features are definitely a way to go.
I've simply used `#[cfg(debug_assertions)` as a way to set the the production (info) and dev. logging (trace) level for anyone interested
